/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "dynamic-button": "transparent",
        "dynamic-button-hovered": "#A6C5E229",
        "dynamic-button-pressed": "#BFDBF847",

        "tw-background": "#cd5a92",
        "tw-background-overlay": "#000000a3",
        "tw-background-list": "#f1f2f4",
        "tw-background-card": "#FFFFFF",

        // input
        "tw-background-input": "#FFFFFF",
        "tw-background-input-hovered": "#F7F8F9",
        "tw-background-input-pressed": "#FFFFFF",
        "tw-background-input-transparent": "transparent",

        // neutral
        "tw-background-neutral": "#091E420F",
        "tw-background-neutral-hovered": "#091E4224",
        "tw-background-neutral-pressed": "#091E424F",
        // danger
        "tw-background-danger": "#C9372C",
        "tw-background-danger-hovered": "#AE2E24",
        "tw-background-danger-pressed": "#5D1F1A",

        // color
        "tw-hovered": "#388BFF",
        "tw-font-neutral": "#172B4D",
        "tw-add-button-neutral": "#ffffff3d",
        "tw-add-button-hovered": "#A6C5E229",
        "tw-add-button-pressed": "#BFDBF847",

        // color-scheme
        "color-scheme": "light",

        // text
        "tw-text": "#172B4D",
        "tw-text-accent-lime": "#4C6B1F",
        "tw-text-accent-lime-bolder": "#37471F",
        "tw-text-accent-red": "#AE2E24",
        "tw-text-accent-red-bolder": "#5D1F1A",
        "tw-text-accent-orange": "#A54800",
        "tw-text-accent-orange-bolder": "#702E00",
        "tw-text-accent-yellow": "#7F5F01",
        "tw-text-accent-yellow-bolder": "#533F04",
        "tw-text-accent-green": "#216E4E",
        "tw-text-accent-green-bolder": "#164B35",
        "tw-text-accent-teal": "#206A83",
        "tw-text-accent-teal-bolder": "#164555",
        "tw-text-accent-blue": "#0055CC",
        "tw-text-accent-blue-bolder": "#09326C",
        "tw-text-accent-purple": "#5E4DB2",
        "tw-text-accent-purple-bolder": "#352C63",
        "tw-text-accent-magenta": "#943D73",
        "tw-text-accent-magenta-bolder": "#50253F",
        "tw-text-accent-gray": "#44546F",
        "tw-text-accent-gray-bolder": "#091E42",
        "tw-text-disabled": "#091E424F",
        "tw-text-inverse": "#FFFFFF",
        "tw-text-selected": "#0C66E4",
        "tw-text-brand": "#0C66E4",
        "tw-text-danger": "#AE2E24",
        "tw-text-warning": "#A54800",
        "tw-text-warning-inverse": "#172B4D",
        "tw-text-success": "#216E4E",
        "tw-text-discovery": "#5E4DB2",
        "tw-text-information": "#0055CC",
        "tw-text-subtlest": "#626F86",
        "tw-text-subtle": "#44546F",

        // link
        "tw-link": "#0C66E4",
        "tw-link-pressed": "#0055CC",
        "tw-link-visited": "#5E4DB2",

        // icon
        "tw-icon": "#44546F",
        "tw-icon-accent-lime": "#6A9A23",
        "tw-icon-accent-red": "#C9372C",
        "tw-icon-accent-orange": "#E56910",
        "tw-icon-accent-yellow": "#B38600",
        "tw-icon-accent-green": "#22A06B",
        "tw-icon-accent-teal": "#2898BD",
        "tw-icon-accent-blue": "#1D7AFC",
        "tw-icon-accent-purple": "#8270DB",
        "tw-icon-accent-magenta": "#CD519D",
        "tw-icon-accent-gray": "#758195",
        "tw-icon-disabled": "#091E424F",
        "tw-icon-inverse": "#FFFFFF",
        "tw-icon-selected": "#0C66E4",
        "tw-icon-brand": "#0C66E4",
        "tw-icon-danger": "#C9372C",
        "tw-icon-warning": "#E56910",
        "tw-icon-warning-inverse": "#172B4D",
        "tw-icon-success": "#22A06B",
        "tw-icon-discovery": "#8270DB",
        "tw-icon-information": "#1D7AFC",
        "tw-icon-subtle": "#626F86",

        // border
        "tw-border": "#091E4224",
        "tw-border-accent-lime": "#6A9A23",
        "tw-border-accent-red": "#E2483D",
        "tw-border-accent-orange": "#E56910",
        "tw-border-accent-yellow": "#B38600",
        "tw-border-accent-green": "#22A06B",
        "tw-border-accent-teal": "#2898BD",
        "tw-border-accent-blue": "#1D7AFC",
        "tw-border-accent-purple": "#8270DB",
        "tw-border-accent-magenta": "#CD519D",
        "tw-border-accent-gray": "#758195",
        "tw-border-disabled": "#091E420F",
        "tw-border-focused": "#388BFF",
        "tw-border-input": "#091E4224",
        "tw-border-inverse": "#FFFFFF",
        "tw-border-selected": "#0C66E4",
        "tw-border-brand": "#0C66E4",
        "tw-border-danger": "#E2483D",
        "tw-border-warning": "#E56910",
        "tw-border-success": "#22A06B",
        "tw-border-discovery": "#8270DB",
        "tw-border-information": "#1D7AFC",
        "tw-border-bold": "#758195",

        // background-accent
        "tw-background-accent-lime-subtlest": "#EFFFD6",
        "tw-background-accent-lime-subtlest-hovered": "#D3F1A7",
        "tw-background-accent-lime-subtlest-pressed": "#B3DF72",
        "tw-background-accent-lime-subtler": "#D3F1A7",
        "tw-background-accent-lime-subtler-hovered": "#B3DF72",
        "tw-background-accent-lime-subtler-pressed": "#94C748",
        "tw-background-accent-lime-subtle": "#94C748",
        "tw-background-accent-lime-subtle-hovered": "#B3DF72",
        "tw-background-accent-lime-subtle-pressed": "#D3F1A7",
        "tw-background-accent-lime-bolder": "#5B7F24",
        "tw-background-accent-lime-bolder-hovered": "#4C6B1F",
        "tw-background-accent-lime-bolder-pressed": "#37471F",
        "tw-background-accent-red-subtlest": "#FFECEB",
        "tw-background-accent-red-subtlest-hovered": "#FFD5D2",
        "tw-background-accent-red-subtlest-pressed": "#FD9891",
        "tw-background-accent-red-subtler": "#FFD5D2",
        "tw-background-accent-red-subtler-hovered": "#FD9891",
        "tw-background-accent-red-subtler-pressed": "#F87168",
        "tw-background-accent-red-subtle": "#F87168",
        "tw-background-accent-red-subtle-hovered": "#FD9891",
        "tw-background-accent-red-subtle-pressed": "#FFD5D2",
        "tw-background-accent-red-bolder": "#C9372C",
        "tw-background-accent-red-bolder-hovered": "#AE2E24",
        "tw-background-accent-red-bolder-pressed": "#5D1F1A",
        "tw-background-accent-orange-subtlest": "#FFF3EB",
        "tw-background-accent-orange-subtlest-hovered": "#FEDEC8",
        "tw-background-accent-orange-subtlest-pressed": "#FEC195",
        "tw-background-accent-orange-subtler": "#FEDEC8",
        "tw-background-accent-orange-subtler-hovered": "#FEC195",
        "tw-background-accent-orange-subtler-pressed": "#FEA362",
        "tw-background-accent-orange-subtle": "#FEA362",
        "tw-background-accent-orange-subtle-hovered": "#FEC195",
        "tw-background-accent-orange-subtle-pressed": "#FEDEC8",
        "tw-background-accent-orange-bolder": "#C25100",
        "tw-background-accent-orange-bolder-hovered": "#A54800",
        "tw-background-accent-orange-bolder-pressed": "#702E00",
        "tw-background-accent-yellow-subtlest": "#FFF7D6",
        "tw-background-accent-yellow-subtlest-hovered": "#F8E6A0",
        "tw-background-accent-yellow-subtlest-pressed": "#F5CD47",
        "tw-background-accent-yellow-subtler": "#F8E6A0",
        "tw-background-accent-yellow-subtler-hovered": "#F5CD47",
        "tw-background-accent-yellow-subtler-pressed": "#E2B203",
        "tw-background-accent-yellow-subtle": "#F5CD47",
        "tw-background-accent-yellow-subtle-hovered": "#E2B203",
        "tw-background-accent-yellow-subtle-pressed": "#CF9F02",
        "tw-background-accent-yellow-bolder": "#946F00",
        "tw-background-accent-yellow-bolder-hovered": "#7F5F01",
        "tw-background-accent-yellow-bolder-pressed": "#533F04",
        "tw-background-accent-green-subtlest": "#DCFFF1",
        "tw-background-accent-green-subtlest-hovered": "#BAF3DB",
        "tw-background-accent-green-subtlest-pressed": "#7EE2B8",
        "tw-background-accent-green-subtler": "#BAF3DB",
        "tw-background-accent-green-subtler-hovered": "#7EE2B8",
        "tw-background-accent-green-subtler-pressed": "#4BCE97",
        "tw-background-accent-green-subtle": "#4BCE97",
        "tw-background-accent-green-subtle-hovered": "#7EE2B8",
        "tw-background-accent-green-subtle-pressed": "#BAF3DB",
        "tw-background-accent-green-bolder": "#1F845A",
        "tw-background-accent-green-bolder-hovered": "#216E4E",
        "tw-background-accent-green-bolder-pressed": "#164B35",
        "tw-background-accent-teal-subtlest": "#E7F9FF",
        "tw-background-accent-teal-subtlest-hovered": "#C6EDFB",
        "tw-background-accent-teal-subtlest-pressed": "#9DD9EE",
        "tw-background-accent-teal-subtler": "#C6EDFB",
        "tw-background-accent-teal-subtler-hovered": "#9DD9EE",
        "tw-background-accent-teal-subtler-pressed": "#6CC3E0",
        "tw-background-accent-teal-subtle": "#6CC3E0",
        "tw-background-accent-teal-subtle-hovered": "#9DD9EE",
        "tw-background-accent-teal-subtle-pressed": "#C6EDFB",
        "tw-background-accent-teal-bolder": "#227D9B",
        "tw-background-accent-teal-bolder-hovered": "#206A83",
        "tw-background-accent-teal-bolder-pressed": "#164555",
        "tw-background-accent-blue-subtlest": "#E9F2FF",
        "tw-background-accent-blue-subtlest-hovered": "#CCE0FF",
        "tw-background-accent-blue-subtlest-pressed": "#85B8FF",
        "tw-background-accent-blue-subtler": "#CCE0FF",
        "tw-background-accent-blue-subtler-hovered": "#85B8FF",
        "tw-background-accent-blue-subtler-pressed": "#579DFF",
        "tw-background-accent-blue-subtle": "#579DFF",
        "tw-background-accent-blue-subtle-hovered": "#85B8FF",
        "tw-background-accent-blue-subtle-pressed": "#CCE0FF",
        "tw-background-accent-blue-bolder": "#0C66E4",
        "tw-background-accent-blue-bolder-hovered": "#0055CC",
        "tw-background-accent-blue-bolder-pressed": "#09326C",
        "tw-background-accent-purple-subtlest": "#F3F0FF",
        "tw-background-accent-purple-subtlest-hovered": "#DFD8FD",
        "tw-background-accent-purple-subtlest-pressed": "#B8ACF6",
        "tw-background-accent-purple-subtler": "#DFD8FD",
        "tw-background-accent-purple-subtler-hovered": "#B8ACF6",
        "tw-background-accent-purple-subtler-pressed": "#9F8FEF",
        "tw-background-accent-purple-subtle": "#9F8FEF",
        "tw-background-accent-purple-subtle-hovered": "#B8ACF6",
        "tw-background-accent-purple-subtle-pressed": "#DFD8FD",
        "tw-background-accent-purple-bolder": "#6E5DC6",
        "tw-background-accent-purple-bolder-hovered": "#5E4DB2",
        "tw-background-accent-purple-bolder-pressed": "#352C63",
        "tw-background-accent-magenta-subtlest": "#FFECF8",
        "tw-background-accent-magenta-subtlest-hovered": "#FDD0EC",
        "tw-background-accent-magenta-subtlest-pressed": "#F797D2",
        "tw-background-accent-magenta-subtler": "#FDD0EC",
        "tw-background-accent-magenta-subtler-hovered": "#F797D2",
        "tw-background-accent-magenta-subtler-pressed": "#E774BB",
        "tw-background-accent-magenta-subtle": "#E774BB",
        "tw-background-accent-magenta-subtle-hovered": "#F797D2",
        "tw-background-accent-magenta-subtle-pressed": "#FDD0EC",
        "tw-background-accent-magenta-bolder": "#AE4787",
        "tw-background-accent-magenta-bolder-hovered": "#943D73",
        "tw-background-accent-magenta-bolder-pressed": "#50253F",
        "tw-background-accent-gray-subtlest": "#F1F2F4",
        "tw-background-accent-gray-subtlest-hovered": "#DCDFE4",
        "tw-background-accent-gray-subtlest-pressed": "#B3B9C4",
        "tw-background-accent-gray-subtler": "#DCDFE4",
        "tw-background-accent-gray-subtler-hovered": "#B3B9C4",
        "tw-background-accent-gray-subtler-pressed": "#8590A2",
        "tw-background-accent-gray-subtle": "#8590A2",
        "tw-background-accent-gray-subtle-hovered": "#B3B9C4",
        "tw-background-accent-gray-subtle-pressed": "#DCDFE4",
        "tw-background-accent-gray-bolder": "#626F86",
        "tw-background-accent-gray-bolder-hovered": "#44546F",
        "tw-background-accent-gray-bolder-pressed": "#2C3E5D",

        // background-disabled
        "tw-background-disabled": "#091E4208",

        // background-input
        "tw-background-input": "#FFFFFF",
        "tw-background-input-hovered": "#F7F8F9",
        "tw-background-input-pressed": "#FFFFFF",

        // background-inverse
        "tw-background-inverse-subtle": "#00000029",
        "tw-background-inverse-subtle-hovered": "#0000003D",
        "tw-background-inverse-subtle-pressed": "#00000052",

        // background-neutral
        "tw-background-neutral": "#091E420F",
        "tw-background-neutral-hovered": "#091E4224",
        "tw-background-neutral-pressed": "#091E424F",
        "tw-background-neutral-subtle": "#00000000",
        "tw-background-neutral-subtle-hovered": "#091E420F",
        "tw-background-neutral-subtle-pressed": "#091E4224",
        "tw-background-neutral-bold": "#44546F",
        "tw-background-neutral-bold-hovered": "#2C3E5D",
        "tw-background-neutral-bold-pressed": "#172B4D",

        // background-selected
        "tw-background-selected": "#E9F2FF",
        "tw-background-selected-hovered": "#CCE0FF",
        "tw-background-selected-pressed": "#85B8FF",
        "tw-background-selected-bold": "#0C66E4",
        "tw-background-selected-bold-hovered": "#0055CC",
        "tw-background-selected-bold-pressed": "#09326C",

        // background-brand
        "tw-background-brand-subtlest": "#E9F2FF",
        "tw-background-brand-subtlest-hovered": "#CCE0FF",
        "tw-background-brand-subtlest-pressed": "#85B8FF",
        "tw-background-brand-bold": "#0C66E4",
        "tw-background-brand-bold-hovered": "#0055CC",
        "tw-background-brand-bold-pressed": "#09326C",
        "tw-background-brand-boldest": "#1C2B41",
        "tw-background-brand-boldest-hovered": "#09326C",
        "tw-background-brand-boldest-pressed": "#0055CC",

        // background-danger
        "tw-background-danger": "#FFECEB",
        "tw-background-danger-hovered": "#FFD5D2",
        "tw-background-danger-pressed": "#FD9891",
        "tw-background-danger-bold": "#C9372C",
        "tw-background-danger-bold-hovered": "#AE2E24",
        "tw-background-danger-bold-pressed": "#5D1F1A",

        // background-warning
        "tw-background-warning": "#FFF7D6",
        "tw-background-warning-hovered": "#F8E6A0",
        "tw-background-warning-pressed": "#F5CD47",
        "tw-background-warning-bold": "#F5CD47",
        "tw-background-warning-bold-hovered": "#E2B203",
        "tw-background-warning-bold-pressed": "#CF9F02",

        // background-success
        "tw-background-success": "#DCFFF1",
        "tw-background-success-hovered": "#BAF3DB",
        "tw-background-success-pressed": "#7EE2B8",
        "tw-background-success-bold": "#1F845A",
        "tw-background-success-bold-hovered": "#216E4E",
        "tw-background-success-bold-pressed": "#164B35",

        // background-discovery
        "tw-background-discovery": "#F3F0FF",
        "tw-background-discovery-hovered": "#DFD8FD",
        "tw-background-discovery-pressed": "#B8ACF6",
        "tw-background-discovery-bold": "#6E5DC6",
        "tw-background-discovery-bold-hovered": "#5E4DB2",
        "tw-background-discovery-bold-pressed": "#352C63",

        // background-information
        "tw-background-information": "#E9F2FF",
        "tw-background-information-hovered": "#CCE0FF",
        "tw-background-information-pressed": "#85B8FF",
        "tw-background-information-bold": "#0C66E4",
        "tw-background-information-bold-hovered": "#0055CC",
        "tw-background-information-bold-pressed": "#09326C",

        // blanket
        "tw-blanket": "#091E427D",
        "tw-blanket-selected": "#388BFF14",
        "tw-blanket-danger": "#EF5C4814",

        // interaction
        "tw-interaction-hovered": "#00000029",
        "tw-interaction-pressed": "#00000052",

        // Skeleton
        "tw-skeleton": "#091E420F",
        "tw-skeleton-subtle": "#091E4208",

        // Chart
        "tw-chart-categorical-1": "#2898BD",
        "tw-chart-categorical-1-hovered": "#227D9B",
        "tw-chart-categorical-2": "#5E4DB2",
        "tw-chart-categorical-2-hovered": "#352C63",
        "tw-chart-categorical-3": "#E56910",
        "tw-chart-categorical-3-hovered": "#C25100",
        "tw-chart-categorical-4": "#943D73",
        "tw-chart-categorical-4-hovered": "#50253F",
        "tw-chart-categorical-5": "#09326C",
        "tw-chart-categorical-5-hovered": "#1C2B41",
        "tw-chart-categorical-6": "#8F7EE7",
        "tw-chart-categorical-6-hovered": "#8270DB",
        "tw-chart-categorical-7": "#50253F",
        "tw-chart-categorical-7-hovered": "#3D2232",
        "tw-chart-categorical-8": "#A54800",
        "tw-chart-categorical-8-hovered": "#702E00",
        "tw-chart-lime-bold": "#6A9A23",
        "tw-chart-lime-bold-hovered": "#5B7F24",
        "tw-chart-lime-bolder": "#5B7F24",
        "tw-chart-lime-bolder-hovered": "#4C6B1F",
        "tw-chart-lime-boldest": "#4C6B1F",
        "tw-chart-lime-boldest-hovered": "#37471F",
        "tw-chart-neutral": "#8590A2",
        "tw-chart-neutral-hovered": "#758195",
        "tw-chart-red-bold": "#F15B50",
        "tw-chart-red-bold-hovered": "#E2483D",
        "tw-chart-red-bolder": "#E2483D",
        "tw-chart-red-bolder-hovered": "#C9372C",
        "tw-chart-red-boldest": "#AE2E24",
        "tw-chart-red-boldest-hovered": "#5D1F1A",
        "tw-chart-orange-bold": "#E56910",
        "tw-chart-orange-bold-hovered": "#C25100",
        "tw-chart-orange-bolder": "#C25100",
        "tw-chart-orange-bolder-hovered": "#A54800",
        "tw-chart-orange-boldest": "#A54800",
        "tw-chart-orange-boldest-hovered": "#702E00",
        "tw-chart-yellow-bold": "#B38600",
        "tw-chart-yellow-bold-hovered": "#946F00",
        "tw-chart-yellow-bolder": "#946F00",
        "tw-chart-yellow-bolder-hovered": "#7F5F01",
        "tw-chart-yellow-boldest": "#7F5F01",
        "tw-chart-yellow-boldest-hovered": "#533F04",
        "tw-chart-green-bold": "#22A06B",
        "tw-chart-green-bold-hovered": "#1F845A",
        "tw-chart-green-bolder": "#1F845A",
        "tw-chart-green-bolder-hovered": "#216E4E",
        "tw-chart-green-boldest": "#216E4E",
        "tw-chart-green-boldest-hovered": "#164B35",
        "tw-chart-teal-bold": "#2898BD",
        "tw-chart-teal-bold-hovered": "#227D9B",
        "tw-chart-teal-bolder": "#227D9B",
        "tw-chart-teal-bolder-hovered": "#206A83",
        "tw-chart-teal-boldest": "#206A83",
        "tw-chart-teal-boldest-hovered": "#164555",
        "tw-chart-blue-bold": "#388BFF",
        "tw-chart-blue-bold-hovered": "#1D7AFC",
        "tw-chart-blue-bolder": "#1D7AFC",
        "tw-chart-blue-bolder-hovered": "#0C66E4",
        "tw-chart-blue-boldest": "#0055CC",
        "tw-chart-blue-boldest-hovered": "#09326C",
        "tw-chart-purple-bold": "#8F7EE7",
        "tw-chart-purple-bold-hovered": "#8270DB",
        "tw-chart-purple-bolder": "#8270DB",
        "tw-chart-purple-bolder-hovered": "#6E5DC6",
        "tw-chart-purple-boldest": "#5E4DB2",
        "tw-chart-purple-boldest-hovered": "#352C63",
        "tw-chart-magenta-bold": "#DA62AC",
        "tw-chart-magenta-bold-hovered": "#CD519D",
        "tw-chart-magenta-bolder": "#CD519D",
        "tw-chart-magenta-bolder-hovered": "#AE4787",
        "tw-chart-magenta-boldest": "#943D73",
        "tw-chart-magenta-boldest-hovered": "#50253F",
        "tw-chart-gray-bold": "#8590A2",
        "tw-chart-gray-bold-hovered": "#758195",
        "tw-chart-gray-bolder": "#758195",
        "tw-chart-gray-bolder-hovered": "#626F86",
        "tw-chart-gray-boldest": "#44546F",
        "tw-chart-gray-boldest-hovered": "#2C3E5D",
        "tw-chart-brand": "#1D7AFC",
        "tw-chart-brand-hovered": "#0C66E4",
        "tw-chart-danger": "#F15B50",
        "tw-chart-danger-hovered": "#E2483D",
        "tw-chart-danger-bold": "#AE2E24",
        "tw-chart-danger-bold-hovered": "#5D1F1A",
        "tw-chart-warning": "#B38600",
        "tw-chart-warning-hovered": "#946F00",
        "tw-chart-warning-bold": "#7F5F01",
        "tw-chart-warning-bold-hovered": "#533F04",
        "tw-chart-success": "#22A06B",
        "tw-chart-success-hovered": "#1F845A",
        "tw-chart-success-bold": "#216E4E",
        "tw-chart-success-bold-hovered": "#164B35",
        "tw-chart-discovery": "#8F7EE7",
        "tw-chart-discovery-hovered": "#8270DB",
        "tw-chart-discovery-bold": "#5E4DB2",
        "tw-chart-discovery-bold-hovered": "#352C63",
        "tw-chart-information": "#388BFF",
        "tw-chart-information-hovered": "#1D7AFC",
        "tw-chart-information-bold": "#0055CC",
        "tw-chart-information-bold-hovered": "#09326C",

        // Surface
        "tw-surface": "#FFFFFF",
        "tw-surface-hovered": "#F1F2F4",
        "tw-surface-pressed": "#DCDFE4",
        "tw-surface-overlay": "#FFFFFF",
        "tw-surface-overlay-hovered": "#F1F2F4",
        "tw-surface-overlay-pressed": "#DCDFE4",
        "tw-surface-raised": "#FFFFFF",
        "tw-surface-raised-hovered": "#F1F2F4",
        "tw-surface-raised-pressed": "#DCDFE4",
        "tw-surface-sunken": "#F7F8F9",

        // Shadow
        "tw-shadow-overflow": "0px 0px 8px #091E4229, 0px 0px 1px #091E421F",
        "tw-shadow-overflow-perimeter": "#091e421f",
        "tw-shadow-overflow-spread": "#091e4229",
        "tw-shadow-overlay": "0px 8px 12px #091E4226, 0px 0px 1px #091E424F",
        "tw-shadow-raised": "0px 1px 1px #091E4240, 0px 0px 1px #091E424F",

        // Opacity
        "tw-opacity-disabled": "0.4",
        "tw-opacity-loading": "0.2",
        "tw-UNSAFE-transparent": "transparent",
        "tw-elevation-surface-current": "#FFFFFF",
      },
      fontFamily: {
        // font-trello (font-{family})
        trello: [
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Noto Sans",
          "Ubuntu",
          "Droid Sans",
          "Helvetica Neue",
          "sans-serif",
        ],
      },
      container: {
        padding: "0 6px",
      },
      screens: {
        md: "750px",
      },
      spacing: {
        "tw-space-0": "0rem",
        "tw-space-025": "0.125rem",
        "tw-space-050": "0.25rem",
        "tw-space-075": "0.375rem",
        "tw-space-100": "0.5rem",
        "tw-space-150": "0.75rem",
        "tw-space-200": "1rem",
        "tw-space-250": "1.25rem",
        "tw-space-300": "1.5rem",
        "tw-space-400": "2rem",
        "tw-space-500": "2.5rem",
        "tw-space-600": "3rem",
        "tw-space-800": "4rem",
        "tw-space-1000": "5rem",
        "tw-space-negative-025": "-0.125rem",
        "tw-space-negative-050": "-0.25rem",
        "tw-space-negative-075": "-0.375rem",
        "tw-space-negative-100": "-0.5rem",
        "tw-space-negative-150": "-0.75rem",
        "tw-space-negative-200": "-1rem",
        "tw-space-negative-250": "-1.25rem",
        "tw-space-negative-300": "-1.5rem",
        "tw-space-negative-400": "-2rem",
      },
      boxShadow: {
        "3xl": "inset 0 0 0 2 #091E4224",
      },
    },
  },
  plugins: [],
};
